### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alfuken** [psoftware/autocraft_1.14.4#1]
Hi. I have a question about the code. All seems clear to me except networking part. What are those packets are used for? Can you give a brief description for each? Thanks!

**Comment by psoftware** [comment]
Hi. I actually don't remember a lot, let me check the code, I'm not modding a lot these days :/

- _TilePacket_ is common code to encode tile entity position when needed in packets. It's inherithed by all packet classes and offers encoding and decoding by defining subEncode and subDecode methods. Position is a key to identify one particular TileAutoCrafter.
- _PacketClientCrafterAction_ encode messages when clients click on arrows and confirms a recipe. Sub Handler class code is server side and decode PacketClientCrafterAction messages sent by the client.
- _PacketServerCrafterAction_ encode server messages in response to PacketClientCrafterAction messages. It's needed to notify the user of recipe and block inventory changes in response to a user action . All nearby players are notified too (to keep their GUI updated). Sub Handler class is client side and does PacketServerCrafterAction decoding for the client.
- _PacketClientRequestAll_ and _PacketServerRequestAll_, they seem to be used when a player opens the block inventory. Client notifies the server that the gui has been opened by the client with a PacketClientRequestAll, which gets a PacketServerRequestAll response that contains TileAutoCrafter status (inventory and recipe). What is not clear to me is why PacketServerRequestAll response is sent also to all the nearby players. I don't know why, it should be unicast. Probably I wanted to implement some kind of GUI opening mutual exclusion that I never done.

There is a lot of improvement that can be done here and that should be evaluated. Maybe it's better to avoid broadcasting GUI notifications to users that are not interacting with the object. However this require the server to know if the client is using the GUI or not, and that requires to send additional messages.
